title: "Tatiana Akopova"

remote_theme: mmistakes/minimal-mistakes@4.25.0
plugins:
  - jekyll-include-cache
tag_archive:
  type: liquid
  path: /tags/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      header:
        teaser: "/assets/images/living-for-the-moment.jpg"
